spring.application.name=is-ticket-service

# database info
spring.datasource.url=jdbc:postgresql://localhost:5432/ticket-service
spring.datasource.username=ticket-service
spring.datasource.password=ticket-admin
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

jwt.secret=superSecretWord12121p31411414141kpamfamfpmafpamoamafmoamfaomfamfa
jwt.expiration=3000000

spring.jackson.serialization.fail-on-empty-beans=false
spring.jackson.datatype.hibernate.enable=true
